version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: isra_postgres
    environment:
      - POSTGRES_DB=isra_production
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=$${ODOO_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 3

  odoo:
    image: odoo:17.0
    container_name: isra_odoo
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=$${ODOO_DB_PASSWORD}
      - POSTGRES_DB=isra_production
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons:ro
      - ./config:/etc/odoo:ro
      - odoo_data:/var/lib/odoo
    restart: unless-stopped
    command: odoo -i base -d isra_production --without-demo=all

volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local

networks:
  default:
    driver: bridge