services:
  postgres:
    image: postgres:15
    container_name: isra_postgres_fresh
    environment:
      - POSTGRES_DB=isra_production
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=isra_postgres{ODOO_DB_PASSWORD}
    volumes:
      - fresh_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    container_name: isra_odoo_fresh
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=isra_postgres{ODOO_DB_PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - fresh_odoo_data:/var/lib/odoo
    restart: unless-stopped

volumes:
  fresh_postgres_data:
    driver: local
  fresh_odoo_data:
    driver: local
