version: '3.8'

services:
  postgres:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    command: postgres -c max_connections=200

  odoo:
    image: odoo:16.0
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
      - DB_MAXCONN=64
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo_data:/var/lib/odoo
    restart: unless-stopped
    command: odoo -c /etc/odoo/odoo.conf

volumes:
  postgres_data:
  odoo_data: